services:
  backend:
    build:
      context: '.'
      dockerfile: ./Dockerfile.test
    container_name: sms-frontend-test-container
    networks:
      - sms-app-test-network
    volumes:
      - ./:/app
    env_file:
      - C:/Users/91987/Desktop/personal/SMS/SECRET/.env
    environment:
      - BACKEND_PORT=${BACKEND_PORT}
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
networks:
  sms-app-test-network:
